work:
    #版本 v1.0老版本,v2.0新版本
    version: tvc
    #线程池大小
    coresize: 20
    #空闲时休眠时间
    sleeptime: 2000
    #数据库抓取大小/每批次
    batchsize: 500
    #发送超时/每批次 单位(秒)
    timeout: 30
    #HTTP 请求头信息 默认
    heads:
      Content-Type: text/xml; charset=UTF-8
      SOAPAction: null
    #作业定义
    works:
    #违规变道业务
    #作业是否启用 true启用,false禁用
    - enabled: true
      #作业类型basic基本业务,
      type: dir2WebserviceWork
      #作业名称
      name: dir2webservice
      #数据发送模版  对应config下template目录下文件名 即WSDL数据模版
      template: dir2webservice
      #SQL脚本对应 config下sql目录下文件名
      sql: dir2webservice
      #WSDL地址即接收方WebService WSDL地址
      datapath: C:/Users/liuyanghe/Desktop/设备对接协议
      fileSfx: ini
      queueCapacity: 10
      iniEncoding: GBK
      url: http://10.150.27.42:8080/tvc-webservice/services/TgsService
 